config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources 'home'
  resources 'users'
  resources 'sessions', only: [:new, :create, :destroy]
  resources 'questions' do
    resources 'answers', except: [:index, :show]
  end

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

end

app/models/answer.rb
class Answer < ActiveRecord::Base

  belongs_to :user
  belongs_to :question

  validates :content, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessor :password
  belongs_to :user
  has_many :answers

  validates :name, presence: true
  validates :name, uniqueness: true
  validates :body, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_many :questions

  validates :password, confirmation: true
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :name, presence: true
  validates :password, presence: true
  before_save :encrypt_password


  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash = BCrypt::Engine.hash_secret(password, user.password_salt)
      return user
    else
      return nil
    end

  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @answer = Answer.new(answer_params)
    @question = Question.find(params[:question_id])
    if @answer.save
      flash[:notice] = "THANK KNOWING. HOPE BRAIN NO HURT MUCH NOW."
        redirect_to question_path(@answer.question)
    else
      render :new
    end
  end

  def update
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    authorize @answer
    if @answer.update(answer_params)
      flash[:alert] = "WHY YOU CHANGE KNOW. HURT DIFFERENT"
      redirect_to question_path(@answer.question)
    else
      render :edit
    end
  end

  def edit
    @answer = Answer.find(params[:id])
    @question = Question.find(params[:question_id])
    authorize @answer
  end

  def destroy
    @answer = Answer.find(params[:id])
    authorize @answer
    @answer.destroy
    flash[:notice] = "GONE. BRAIN STILL HURT"
    redirect_to question_path(@answer.question)
  end

  private def answer_params
    params.require(:answer).permit(:content, :user_id, :question_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  rescue_from Pundit::NotDefinedError, with: :not_logged_in
  private

  def user_not_authorized
    flash[:alert] = "YOU NO DO. BAD. YOU GET STRONGER MAYBE DO LATER"
    redirect_to(request.referrer || root_path)
  end

  def not_logged_in
    flash[:alert] = "YOU NO GO HERE. CAVE ENTER MAYBE GO"
    redirect_to log_in_path
  end

  helper_method :current_user

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      flash[:notice] = "BRAIN HURT NOW. WHY DO THIS"
        redirect_to question_path(@question)
    else
      render :new
    end
  end

  def update
    @question = Question.find(params[:id])
    authorize @question
    if @question.update(question_params)
      flash[:alert] = "BRAIN HURT DIFFERENT"
        redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    authorize @question
  end

  def edit
    @question = Question.find(params[:id])
    authorize @question
  end

  def destroy
    @question = Question.find(params[:id])
    authorize @question
    @question.destroy
    flash[:notice] = "#{@question.name} GONE. BRAIN HURT NO AS MUCH"
    redirect_to questions_path
  end

  private def question_params
    params.require(:question).permit(:name, :body, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "WELCOME IN CAVE"
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "PROBLEM LOG IN. TRY NEW TIME"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "YOU LEAVE CAVE. BYE."
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "WELCOME PEASANT"
      if current_user && current_user.is_admin
        redirect_to users_path
      else
        redirect_to log_in_path
      end
    else
      # flash[:notice] = "YOU DONE MESSED UP. OR MAYBE WE DID. YOU GO BACK NOW"
      render :new
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:alert] = "MANS DIFFERENT"
      if current_user && current_user.is_admin
        redirect_to users_path
      else
        redirect_to user_path(@user)
      end
    else
      render :edit
    end
  end

  def index
    @users = User.all
    authorize current_user
  end

  def show
    @user = User.find(params[:id])
    authorize current_user
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy
    flash[:notice] = "#{@user.name} BYE BYE"

    if current_user == @user
      session.destroy
      redirect_to root_path
    elsif current_user && current_user.is_admin
      redirect_to users_path
    end
  end

  private def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_form.html.erb
<%= render 'layouts/errors', object: @answer %>

<%= bootstrap_form_for([@question, @answer]) do |f| %>
  <%= f.text_area :content, placeholder: "They need to do way instain mother> who kill thier babbys. becuse these babby cant frigth back? it was on the news this mroing a mother in ar who had kill her three kids. they are taking the three babby back to new york too lady to rest my pary are with the father who lost his children ; i am truley sorry for your lots" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.hidden_field :question_id, value: @question.id %>
  <%= f.submit data: {disable_with: "Hail Satan..." }, class: "btn btn-success btn-block" %>
<% end %>

app/views/answers/edit.html.erb
<% content_for(:title, "MAKE DIFFERENT") %>

<h1>MAKE DIFFERENT</h1>

<%= render 'form' %>

app/views/answers/new.html.erb
<% content_for(:title, "NEW BRAIN HELP") %>

<h1>NEW BRAIN HELP</h1>
<h3><%= @question.body %></h3>

<%= render 'form' %>

app/views/home/index.html.erb
<% content_for(:title, "CAVE FLOW OVER") %>

<h1>WELKUM FLOW OVER 4 CAVE MENS</h1>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>

  <% content_for(:title, "YOU WRONG!!!!") %>
  <div class="text-center">

  <h3>YOU MAKE PROBLEM</h3>
  <!-- <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul> -->
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <div class="panel panel-defalt">

  <div class="text-center bold">
    <% if current_user %>
      <p> YOU AM - <%= current_user.name %> </p>
    <% end %>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
  </div>

  <%= yield %>
  </div>
</div>
 <nav class='navbar navbar-default' role='navigation' id="nav-footer">
    <ul class='nav navbar-nav'>
      <% if current_user %>
          <li><%= link_to "YOU CAVE", user_path(current_user) %></li>
        <% if current_user.is_admin %>
          <li><%= link_to "CAVE MENS", users_path %></li>
          <li><%= link_to "NEW CAVE MENS", new_user_path %></li>
        <% end %>
        <li><%= link_to "CAVE LEAVE", log_out_path %></li>
        <li><%= link_to "BRAIN HURTS", questions_path %></li>
        <li><%= link_to "NEW BRAIN HURT", new_question_path %></li>
      <% else %>
         <li><%= link_to "I NEW CAVE MAN", new_user_path %></li>
         <li><%= link_to "CAVE ENTER", log_in_path %></li>
      <% end %>
   </ul>
 </nav>

</body>
</html>

app/views/questions/_form.html.erb
<%= render 'layouts/errors', object: @question %>

<%= bootstrap_form_for(@question) do |f| %>
  <%= f.text_field :name, placeholder: "Question Name" %>
  <%= f.text_area :body, placeholder: "HOW IS BABY FORMED" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit data: {disable_with: "Hail Satan..." }, class: "btn btn-success btn-block" %>
<% end %>

app/views/questions/edit.html.erb
<% content_for(:title, "MAKE DIFFERENT " + @question.name) %>

<h1>MAKE DIFFERENT - <%= @question.name %></h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<% content_for(:title, "ALL CAVE BRAIN HURTS") %>

<h1>ALL CAVE BRAIN HURTS</h1>

<% @questions.all.each do |question| %>
  <ul>
    <li>
      <%= link_to question.name, question_path(question) %>
        <% if current_user %>
          <% if current_user.is_admin || current_user == question.user %>
             <%= link_to edit_question_path(question) do %>
              <span class="glyphicon glyphicon-edit orange"></span>
             <% end %>
             <%= link_to question_path(question), data: {confirm: "FIRE BRAIN HURT?", method: 'delete'} do %>
              <span class="glyphicon glyphicon-fire red"></span>
            <% end %>
          <% end %>
        <% end %>
    </li>
  </ul>
<% end %>

app/views/questions/new.html.erb
<% content_for(:title, "NEW BRAIN HURT") %>

<h1>NEW BRAIN HURT</h1>

<%= render 'form' %>

app/views/questions/show.html.erb
<% content_for(:title, @question.name) %>

<h1><%= @question.name %></h1>

<em class="author"><%=link_to @question.user.name, user_path(@question.user) %> need know</em>

<br><br>

<p>
  <%= @question.body %>
</p>

<% @question.answers.each do |answer| %>
  <ul>
    <li>
      <%= answer.user.name %> SAY - <%= answer.content %>
       <% if current_user.is_admin || current_user == answer.user %>
        <%= link_to edit_question_answer_path(@question, answer), id: "edit_answer#{answer.id}" do %>
         <span class="glyphicon glyphicon-edit orange"></span>
        <% end %>
        <%= link_to question_answer_path(@question, answer), id: "delete_answer#{answer.id}", data: {confirm: "FIRE BRAIN HELP?", method: 'delete'} do %>
         <span class="glyphicon glyphicon-fire red"></span>
         <% end %>
       <% end %>
   </li>
  </ul>
<% end %>

<% if current_user %>
  <% if current_user.is_admin || current_user == @question.user %>
    <div class="btn-group btn-group-sm " role="group">
      <%= link_to "CHANGE", edit_question_path(@question), class: "btn btn-warning" %>
      <%= link_to "FIRE", question_path(@question), class: "btn btn-danger",
                                        data: {confirm: "FIRE BRAIN HURT?",
                                                method: 'delete'} %>
    </div>
  <% end %>
<% end %>


  <%= link_to "ME KNOW", new_question_answer_path(@question), class: "btn btn-success"  %>

app/views/users/_form.html.erb
<%= render 'layouts/errors', object: @user %>

<%= bootstrap_form_for(@user) do |f| %>
  <%= f.text_field :name, placeholder: "User Name" %>
  <%= f.email_field :email, placeholder: "llamaKing@LammasR.us" %>
  <%= f.password_field :password, placeholder: "SUPER SECURE PASSWERD" %>
  <%= f.password_field :password_confirmation, placeholder: "SAME SUPER SECURE PASSWERD"%>
  <% if current_user && current_user.is_admin %>
    <%= f.check_box :is_admin %>
  <% end %>
  <%= f.submit data: {disable_with: "Hail Satan..." }, class: "btn btn-success btn-block" %>
<% end %>

app/views/users/edit.html.erb
<% content_for(:title, "MAKE DIFFERENT " + @user.name) %>

<h1>MAKE DIFFERENT - <%= @user.name %></h1>

<%= render 'form' %>

app/views/users/index.html.erb
<% content_for(:title, "ALL CAVE MANS") %>

<h1>ALL CAVE MANS</h1>

<% @users.all.each do |user| %>
  <ul>
    <li>
        <%= link_to user.name, user_path(user) %>       <%= link_to edit_user_path(user) do %>
          <span class="glyphicon glyphicon-edit orange"></span>
        <% end %>
        <%= link_to user_path(user), data: {confirm: "FIRE CAVE MANS?", method: 'delete'} do %>
          <span class="glyphicon glyphicon-fire red"></span>
        <% end %>
        <% if user.is_admin %>
          <span class="glyphicon glyphicon-eye-open green"></span>
        <% end %>
    </li>
  </ul>
<% end %>

app/views/users/new.html.erb
<% content_for(:title, "NEW CAVE MANS") %>

<h1>NEW CAVE MENS</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>

<h1><%= @user.name %></h1>

<p>
  <%= @user.email %>
</p>

<h3>brain hurts:</h3>

<ul>
  <% @user.questions.each do |question| %>
    <li>
      <%= link_to question.name, question_path(question) %>
      <% if current_user.is_admin || current_user == question.user %>
         <%= link_to edit_question_path(question) do %>
          <span class="glyphicon glyphicon-edit orange"></span>
         <% end %>
         <%= link_to question_path(question), data: {confirm: "FIRE BRAIN HURT?", method: 'delete'} do %>
          <span class="glyphicon glyphicon-fire red"></span>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>
<% if current_user %>
  <% if current_user.is_admin || current_user == @user %>
    <div class="btn-group btn-group-sm " role="group">
      <%= link_to "CHANGE", edit_user_path(@user), class: "btn btn-warning" %>
      <%= link_to "FIRE", user_path(@user), class: "btn btn-danger",
                                        data: {confirm: "FIRE CAVE MANS?",
                                                method: 'delete'} %>
    </div>
  <% end %>
<% end %>